### ISSUE TITLE
node-fetch version 

### ISSUE THREAD

**Issue by fmarcosh** [alitayin/Staking-Reward-Distributor#1]
First of all I want to thank you for your work, for that particular tool and more globally in eCash ecosystem. I don't know if you are paid by GNC or other but you deserve it.

I have tried to use your staking reward distribution tool and after "git clone" and "npm install" I have had the following issues:
1 First run it say dotenv was not found ("Error: Cannot find module 'dotenv'"). Solved with "npm install dotenv"
2 Second run it say node-fetch was not found. Solved with "npm install node-fetch"
3 Third run it say "Error [ERR_REQUIRE_ESM]: require() of ES Module" in "const fetch = require('node-fetch');" sentence. After googling I modify the package.json and change the node-fetch from ">3.3.2" to "2.6.6".

With all these "fixes" the "node app.js" is able to launch but It seems it's not reading my custom ".env" file with my address and key.
The tools is able to load the avalanche proof of my node and save the payout distribution for the future.
My environment is node --version v18.16.0 npm -version 9.5.1 and Ubuntu 22.04.3 LTS

Thanks again

**Comment by fmarcosh** [comment]
After more tries I found that once a proof is loaded the payout address is the right one in the config.json file, so it seems it's working as expected (I need to wait the incoming rewards to verify it), but I have a dude. The eCash address in the .env it's the incoming reward address or anyother address that should recieve the "fees" when distribution percentaje is less than 1?

**Comment by alitayin** [comment]
fixed. just uninstall node-fetch, we don't need that

**Comment by fmarcosh** [comment]
TY

**Comment by fmarcosh** [comment]
TY
